# Generated by Django 4.1.5 on 2023-02-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_addproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
