# Generated by Django 4.1.5 on 2023-02-02 23:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_addproject_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='id',
        ),
        migrations.AlterField(
            model_name='addproject',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
