# Generated by Django 4.1.5 on 2023-02-05 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_result_id_alter_result_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='project_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.PROTECT, to='app.result'),
        ),
        migrations.AlterField(
            model_name='result',
            name='project_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.PROTECT, to='app.project'),
        ),
    ]
